--- #YAML:1.0
name:                Win32-PowerPoint
version:             0.08
abstract:            helps to convert texts to PP slides
license:             perl
author:              
    - Kenichi Ishigaki <ishigaki@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Class::Accessor:               0
    Exporter::Lite:                0
    File::Spec:                    0
    Test::More:                    0
    Win32::OLE:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
