--- #YAML:1.0
name:               Win32-PowerPoint
version:            0.09
abstract:           helps to convert texts to PP slides
author:
    - Kenichi Ishigaki <ishigaki@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor:      0
    Exporter::Lite:       0
    File::Spec:           0
    Test::More:           0.47
    Test::UseAllModules:  0.09
    Win32::OLE:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
